### ISSUE TITLE
IndexOutOfBoundsException when player joins (command issue)

### ISSUE THREAD

**Issue by EpicPlayerA10** [Minestom/Minestom#1080]
When player joins to the server with registered command below with special syntaxes, it gives me an error.
```
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.minestom.server.command.CommandManager.createCommandNodes(CommandManager.java:348)
	at net.minestom.server.command.CommandManager.serializeCommand(CommandManager.java:250)
	at net.minestom.server.command.CommandManager.buildPacket(CommandManager.java:196)
	at net.minestom.server.command.CommandManager.createDeclareCommandsPacket(CommandManager.java:170)
	at net.minestom.server.entity.Player.refreshCommands(Player.java:454)
	at net.minestom.server.entity.Player.UNSAFE_init(Player.java:274)
	at net.minestom.server.network.ConnectionManager.lambda$updateWaitingPlayers$5(ConnectionManager.java:266)
	at org.jctools.queues.MessagePassingQueueUtil.drain(MessagePassingQueueUtil.java:39)
	at org.jctools.queues.BaseMpscLinkedArrayQueue.drain(BaseMpscLinkedArrayQueue.java:638)
	at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:23)
	at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:63)
	at net.minestom.server.network.ConnectionManager.updateWaitingPlayers(ConnectionManager.java:256)
	at net.minestom.server.ServerProcessImpl$TickerImpl.tick(ServerProcessImpl.java:283)
	at net.minestom.server.thread.TickSchedulerThread.run(TickSchedulerThread.java:24)
```
Command code:
```java
        var target = ArgumentType.Literal("target");
        var attribute = ArgumentType.Literal("attribute");
        var get = ArgumentType.Literal("get");

        var scale = ArgumentType.Literal("scale");

        addSyntax(((sender, context) -> {

        }), target, attribute,scale, get);

        var value = ArgumentType.Literal("value");

        addSyntax(((sender, context) -> {

        }), target, attribute,scale, get, value);

        var modifier = ArgumentType.Literal("modifier");

        var someArg = ArgumentType.Literal("someArg");

        addSyntax(((sender, context) -> {

        }), target, attribute, scale, modifier, get, someArg);
```

**Comment by TheMeinerLP** [comment]
Tested with Following Code:
```java
public final class IndexOutOfBoundsExceptionAtJoinCommand extends Command {

    public IndexOutOfBoundsExceptionAtJoinCommand() {
        super("Issue#1080");
        var target = ArgumentType.Literal("target");
        var attribute = ArgumentType.Literal("attribute");
        var get = ArgumentType.Literal("get");

        var scale = ArgumentType.Literal("scale");

        addSyntax(((sender, context) -> {

        }), target, attribute,scale, get);

        var value = ArgumentType.Literal("value");

        addSyntax(((sender, context) -> {

        }), target, attribute,scale, get, value);

        var modifier = ArgumentType.Literal("modifier");

        var someArg = ArgumentType.Literal("someArg");

        addSyntax(((sender, context) -> {

        }), target, attribute, scale, modifier, get, someArg);
    }
}
```
Console log:
```
11:17:27.049 [main] INFO net.minestom.server.ServerProcessImpl - Starting Minestom server.
11:17:27.051 [main] INFO net.minestom.server.ServerProcessImpl - Minestom server started successfully.
11:17:36.062 [] INFO net.minestom.server.MinecraftServer - UUID of player TheMeinerLP is 05bf52c6-7bb0-4f13-8951-0e1fd803df35
```

Proof:

![Image](https://github.com/user-attachments/assets/655f2f3b-7aab-4d2d-9596-1ce999d3058d)

Additional Comments:
If the issue is still happening, please open another issue.
