### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by RAIXOCZ** [Minestom/Minestom#1150]
Hi, I'm having issue with minestom. It's happening when my server auto restarts (feature of my hosting), so nobody tried to connect. But my hosting is making a ping request every 10 seconds or so. And that might cause the issue, but it's only my assumption.

Here is the stacktrace:
```
[main] [04:05:05] (ServerProcessImpl.start) - INFO - Starting Minestom server.
[main] [04:05:05] (ServerProcessImpl.start) - INFO - Minestom server started successfully.
Exception in thread "Ms-entrypoint" java.lang.OutOfMemoryError: Cannot reserve 262143 bytes of direct buffer memory (allocated: 2147221526, limit: 2147483648)
at java.base/java.nio.Bits.reserveMemory(Unknown Source)
at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
at net.minestom.server.utils.binary.BinaryBuffer.ofSize(BinaryBuffer.java:33)
at net.minestom.server.utils.ObjectPool.lambda$static$0(ObjectPool.java:25)
at net.minestom.server.utils.ObjectPool.get(ObjectPool.java:44)
at net.minestom.server.network.player.PlayerSocketConnection.<init>(PlayerSocketConnection.java:77)
at net.minestom.server.network.socket.Worker.receiveConnection(Worker.java:109)
at net.minestom.server.network.socket.Server.lambda$start$1(Server.java:81)
at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(Unknown Source)
at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(Unknown Source)
at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(Unknown Source)
at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(Unknown Source)
at java.base/sun.nio.ch.SelectorImpl.select(Unknown Source)
at net.minestom.server.network.socket.Server.lambda$start$2(Server.java:75)
at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by TheMode** [comment]
I do not know if this is really the reason behind the OOM, but it has mostly been fixed by 2289cf32e13b21fd682161635745a9a104076d73
