### ISSUE TITLE
NPE on localBuffer

### ISSUE THREAD

**Issue by HSGamer** [Minestom/Minestom#1157]
```
java.lang.NullPointerException: Cannot invoke "net.minestom.server.utils.binary.BinaryBuffer.capacity()" because "localBuffer" is null
        at net.minestom.server.network.player.PlayerSocketConnection.writeBufferSync0(PlayerSocketConnection.java:408)
        at net.minestom.server.network.player.PlayerSocketConnection.writeBufferSync(PlayerSocketConnection.java:403)
        at net.minestom.server.network.player.PlayerSocketConnection.lambda$write$3(PlayerSocketConnection.java:176)
        at org.jctools.queues.MessagePassingQueueUtil.drain(MessagePassingQueueUtil.java:53)
        at org.jctools.queues.MpUnboundedXaddArrayQueue.drain(MpUnboundedXaddArrayQueue.java:435)
        at org.jctools.queues.MpscUnboundedXaddArrayQueue.drain(MpscUnboundedXaddArrayQueue.java:28)
        at net.minestom.server.network.socket.Worker.run(Worker.java:46)
```
I don't know why this occurs. It's just randomly spamming my console.

**Comment by TheMode** [comment]
Should be fixed by 20dcf91f4a931da348a1754d91d9a2fb18ae5319
