### ISSUE TITLE
Missing field named 'DataVersion'

### ISSUE THREAD

**Issue by para-dise** [Minestom/Minestom#1175]
Hi, 

I've got an issue with loading a world in Minestom (the world was made for 1.7.10, I recently loaded it in Minecraft 1.18 to update it) and after I join I seem to get 
```
> org.jglrxavpok.hephaistos.mca.AnvilException: Missing field named 'DataVersion' (or of wrong type)
        at org.jglrxavpok.hephaistos.mca.AnvilException$Companion.missing(AnvilException.kt:15)
        at org.jglrxavpok.hephaistos.mca.ChunkColumn.<init>(ChunkColumn.kt:116)
        at org.jglrxavpok.hephaistos.mca.RegionFile.readColumn(RegionFile.kt:184)
        at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk$lambda-3(RegionFile.kt:110)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk(RegionFile.kt:110)
        at net.minestom.server.instance.AnvilLoader.loadMCA(AnvilLoader.java:79)
        at net.minestom.server.instance.AnvilLoader.loadChunk(AnvilLoader.java:68)
        at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$9(InstanceContainer.java:261)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

Here's a link to the map: https://void.cat/3gu7VpD4RYpe3gWDyKsZyW

It works fine in single player and with spigot, so im not sure what the issue is

**Comment by Tynopia** [comment]
I have the same problem with these maps:
https://www.breadbuilds.com/

**Comment by fishermedders** [comment]
Has there been any updates on this? I have tried to load a world into 1.19 to 'update' it, and still get this `AnvilException`.

Thanks

**Comment by fishermedders** [comment]
Welp, a little more digging and I found [this tool](https://github.com/Querz/mcaselector).

In the software, go to `Tools` -> `Change fields` -> then set the [data version](https://minecraft.fandom.com/wiki/Data_version) to whatever your current data version is (1.19.2 is 3120).

This worked a charm.
