### ISSUE TITLE
Wrong client packets could kill server

### ISSUE THREAD

**Issue by RinesThaix** [Minestom/Minestom#1205]
For example, `ClientEntityActionPacket` on init reads an array index and if it exceeds the length, `ArrayIndexOutOfBoundsException` will be thrown. It won't be caught anywhere and `Worker`'s selector will die, therefore switching the server to an unusable state.

Trace:
```
java.lang.ArrayIndexOutOfBoundsException: Index 17 out of bounds for length 9
        at net.minestom.server.network.packet.client.play.ClientEntityActionPacket.<init>(ClientEntityActionPacket.java:11)
        at net.minestom.server.network.packet.client.ClientPacketsHandler.create(ClientPacketsHandler.java:35)
        at net.minestom.server.network.PacketProcessor.create(PacketProcessor.java:32)
        at net.minestom.server.network.PacketProcessor.process(PacketProcessor.java:43)
        at net.minestom.server.network.player.PlayerSocketConnection.lambda$processPackets$0(PlayerSocketConnection.java:112)
        at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:193)
        at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:107)
        at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:77)
        at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:294)
        at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:195)
        at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:135)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:161)
```

It's not just a problem with that specific packet. For example, there's another trace:
```
java.lang.IndexOutOfBoundsException: Range [30, 30 + -1) out of bounds for length 2097151
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
        at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
        at java.base/java.util.Objects.checkFromIndexSize(Objects.java:411)
        at java.base/java.nio.DirectByteBuffer.slice(DirectByteBuffer.java:255)
        at java.base/java.nio.DirectByteBuffer.slice(DirectByteBuffer.java:40)
        at net.minestom.server.utils.binary.BinaryBuffer.asByteBuffer(BinaryBuffer.java:144)
        at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:184)
        at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:107)
        at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:77)
        at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:294)
        at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:195)
        at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:135)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:161)
        at net.minestom.server.network.socket.Worker.run(Worker.java:58)
```

A possible solution would be to catch any throwables within selector's lambda.

**Comment by RinesThaix** [comment]
An issue still persists, but I wasn't able to figure out what exactly happens (and couldn't take a threaddump or any kind of snapshot). What I saw in my log file is that everything was ok, then that exception happened:
```
> java.lang.IndexOutOfBoundsException: Range [42, 42 + -5) out of bounds for length 2097151
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
        at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
        at java.base/java.util.Objects.checkFromIndexSize(Objects.java:411)
        at java.base/java.nio.DirectByteBuffer.slice(DirectByteBuffer.java:255)
        at java.base/java.nio.DirectByteBuffer.slice(DirectByteBuffer.java:40)
        at net.minestom.server.utils.binary.BinaryBuffer.asByteBuffer(BinaryBuffer.java:144)
        at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:183)
        at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:106)
        at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:79)
        at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:294)
        at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:195)
        at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:135)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:161)
        at net.minestom.server.network.socket.Worker.run(Worker.java:59)
```
After that there is not any exceptions or disconnection notifications (that I write on `PlayerDisconnectEvent`), but 15 seconds later players that were online started trying to reconnect (messages from `AsyncPlayerPreLoginEvent` started to appear).

What's especially interesting is the fact that a very similar exceptions appeared earlier after the fix, but such a behaviour didn't happen:
```
> java.lang.IndexOutOfBoundsException: Range [38, 38 + -1) out of bounds for length 2097151
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
        at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
        at java.base/java.util.Objects.checkFromIndexSize(Objects.java:411)
        at java.base/java.nio.DirectByteBuffer.slice(DirectByteBuffer.java:255)
        at java.base/java.nio.DirectByteBuffer.slice(DirectByteBuffer.java:40)
        at net.minestom.server.utils.binary.BinaryBuffer.asByteBuffer(BinaryBuffer.java:144)
        at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:183)
        at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:106)
        at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:79)
        at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:294)
        at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:195)
        at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:135)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:161)
        at net.minestom.server.network.socket.Worker.run(Worker.java:59)
```

I created #1211 in order to try to fix that issue again, but don't know yet whether it helps or not: last crash happened after like 2 days of server uptime.

**Comment by RinesThaix** [comment]
I've just got new trace after which server dies in a described way:
```
> java.util.zip.DataFormatException: invalid code -- missing end-of-block
        at java.base/java.util.zip.Inflater.inflateBufferBuffer(Native Method)
        at java.base/java.util.zip.Inflater.inflate(Inflater.java:546)
        at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:187)
        at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:106)
        at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:79)
        at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:294)
        at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:195)
        at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:135)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:161)
        at net.minestom.server.network.socket.Worker.run(Worker.java:59)
```
