### ISSUE TITLE
ConcurrentModificationException on TickThread

### ISSUE THREAD

**Issue by RinesThaix** [Minestom/Minestom#1212]
It seems to not break anything, but it happens.
```
> java.util.ConcurrentModificationException
        at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
        at net.minestom.server.thread.TickThread.tick(TickThread.java:59)
        at net.minestom.server.thread.TickThread.run(TickThread.java:41)
```

**Comment by TheMeinerLP** [comment]
Can you provide some example code ? Or code of reproduce ?
