### ISSUE TITLE
ArrayIndexOutOfBoundsException: Unable to load world

### ISSUE THREAD

**Issue by ZakShearman** [Minestom/Minestom#1388]
Getting the following error:

```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 24
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680)
	at net.minestom.server.instance.DynamicChunk.getSection(DynamicChunk.java:110)
	at net.minestom.server.instance.AnvilLoader.loadSections(AnvilLoader.java:169)
	at net.minestom.server.instance.AnvilLoader.loadMCA(AnvilLoader.java:130)
	at net.minestom.server.instance.AnvilLoader.loadChunk(AnvilLoader.java:91)
	at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$9(InstanceContainer.java:264)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

This is the result of this error, missing chunks: 
![image](https://user-images.githubusercontent.com/34372536/188674885-39eac88c-6278-4800-a17c-38bcd6451010.png)

The world loads fine on Paper: 
![image](https://user-images.githubusercontent.com/34372536/188669715-7f0eb04e-6650-48f4-af2d-8a1bc78197c4.png)

World also displays fine in Amulet: 
![image](https://user-images.githubusercontent.com/34372536/188673200-5ffc5f68-44de-4476-862e-51db5464f452.png)

World: https://zak.pink/2022/09/empires-broken-1_19-world.zip

**Comment by ZakShearman** [comment]
If it helps, all region files can be deleted apart from `0.0` and `-1.0`. The others are irrelevant to this world.

**Comment by GreatWyrm** [comment]
Does this error still occur with the if you try it with commit caaad1693e67d1657640b5f67134100236570fbb?

**Comment by richgrov** [comment]
I also had this issue and updating to the latest commit seems to have fixed it.
