### ISSUE TITLE
java.lang.UnsupportedOperationException: No format processor for org.jboss.shrinkwrap.resolver.api.maven.MavenResolvedArtifact was found.  when loading an extension with external dependencies.

### ISSUE THREAD

**Issue by kz-n** [Minestom/Minestom#1443]
```
[main] [16:15:30] (ExtensionManager.loadDependencies) - ERROR - This is the exception: java.lang.UnsupportedOperationException: No format processor for org.jboss.shrinkwrap.resolver.api.maven.MavenResolvedArtifact was found. Supported processors are: class org.jboss.shrinkwrap.resolver.impl.maven.archive.ArchiveFormatProcessor
        at org.jboss.shrinkwrap.resolver.spi.format.FormatProcessors.find(FormatProcessors.java:53)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenFormatStageImpl.as(MavenFormatStageImpl.java:84)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenFormatStageImpl.asResolvedArtifact(MavenFormatStageImpl.java:71)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenFormatStageImpl.asResolvedArtifact(MavenFormatStageImpl.java:40)
        at net.minestom.dependencies.maven.MavenResolver.resolve(MavenResolver.kt:62)
        at net.minestom.dependencies.DependencyGetter.get(DependencyGetter.kt:25)
        at net.minestom.server.extensions.ExtensionManager.loadDependencies(ExtensionManager.java:615)
        at net.minestom.server.extensions.ExtensionManager.loadExtensions(ExtensionManager.java:233)
        at net.minestom.server.extensions.ExtensionManager.start(ExtensionManager.java:115)
        at net.minestom.server.ServerProcessImpl.start(ServerProcessImpl.java:211)
        at net.minestom.server.MinecraftServer.start(MinecraftServer.java:323)
        at net.minestom.server.MinecraftServer.start(MinecraftServer.java:328)
        at net.kz_n.basicminestomserver.MinestomServer.main(MinestomServer.java:30)
```

My extension.json is

```json
{
  "entrypoint": "net.kz_n.projectzenith.ZenithExtension",
  "name": "Zenith",
  "version": "1.0.0",
  "externalDependencies": {
    "repositories": [
      {"name": "Central", "url": "https://repo1.maven.org/maven2/"}
    ],
    "artifacts": [
      "net.kyori:adventure-text-minimessage:4.11.0"
    ]
  }
}
```

and `adventure-text-minimessage` is set to compileOnly in my build.gradle

I'm using Minestom `-SNAPSHOT`, so latest commit at the time of writing

**Comment by jhooc77** [comment]
```
implementation 'com.github.Minestom:-SNAPSHOT' {
    exclude group: "org.jboss.shrinkwrap.resolver"
    exclude group: "shrinkwrap-resolver-depchain"
}
implementation group: 'org.jboss.shrinkwrap.resolver', name: 'shrinkwrap-resolver-impl-maven', version: '3.1.4'
```
set like this in your server's gradle.build
