### ISSUE TITLE
Entity#remove on a manual view entity causes ConcurrentModificationException

### ISSUE THREAD

**Issue by ZakShearman** [Minestom/Minestom#1526]
Exception:
```
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$KeyIterator.next(Unknown Source)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at net.minestom.server.entity.EntityView.forManuals(EntityView.java:99)
	at net.minestom.server.entity.Entity.removeFromInstance(Entity.java:907)
	at net.minestom.server.entity.Entity.remove(Entity.java:1488)
	at pink.zak.minestom.towerdefence.model.mob.living.DamageIndicator.tick(DamageIndicator.java:63)
	at net.minestom.server.thread.TickThread.tick(TickThread.java:66)
	at net.minestom.server.thread.TickThread.run(TickThread.java:41)
```

Conditions: There are more than one players viewing the entity

Minimal reproducer:
```java
Entity entity = new Entity(EntityType.AREA_EFFECT_CLOUD);
entity.setAutoViewable(false);
MinecraftServer.getConnectionManager().getOnlinePlayers().forEach(entity::addViewer);

entity.scheduleRemove(20, TimeUnit.SERVER_TICK);
```

Emortal's writing a test rn 😃

**Comment by Obyvante** [comment]
What about using for "manualViewers" field in "EntityView.java"?
```java
Collections.synchronizedSet(new HashSet<>())
```

It seems working for me.

**Comment by TheMeinerLP** [comment]
Is this bug still happend ?
