### ISSUE TITLE
ConcurrentModificationException on entity remove

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#1551]
java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at net.minestom.server.entity.EntityView.forManuals(EntityView.java:99)
	at net.minestom.server.entity.Entity.removeFromInstance(Entity.java:907)
	at net.minestom.server.entity.Entity.remove(Entity.java:1488)
	at net.minestom.server.entity.Player.remove(Player.java:500)

Occured when i use `Entity#remove()`

I have also removed all viewers and it is empty at the time when the remove Method is called

**Comment by ZakShearman** [comment]
Possibly a duplicate of #1526 although I'm not sure as I couldn't cause the issue with < 2 viewers whereas this seems to occur no matter what.

**Comment by einfachBlu** [comment]
Yep, seems exactly as my case. For me it occured for 1 Player as a Viewer. Gonna close this because its just a duplicate.
