### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#1586]
```
java.lang.IndexOutOfBoundsException
        at java.base/java.nio.Buffer.checkIndex(Buffer.java:743)
        at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:332)
        at net.minestom.server.network.NetworkBufferTypes.lambda$static$1(NetworkBufferTypes.java:32)
        at net.minestom.server.network.NetworkBuffer.read(NetworkBuffer.java:101)
        at net.minestom.server.network.NetworkBuffer.readOptional(NetworkBuffer.java:119)
        at net.minestom.server.network.packet.client.login.LoginStartPacket.<init>(LoginStartPacket.java:34)
        at net.minestom.server.network.packet.client.ClientPacketsHandler.create(ClientPacketsHandler.java:35)
        at net.minestom.server.network.PacketProcessor.create(PacketProcessor.java:33)
        at net.minestom.server.network.PacketProcessor.process(PacketProcessor.java:45)
        at net.minestom.server.network.player.PlayerSocketConnection.lambda$processPackets$0(PlayerSocketConnection.java:109)
        at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:230)
        at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:103)
        at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:79)
        at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:294)
        at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:195)
        at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:135)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:161)
        at net.minestom.server.network.socket.Worker.run(Worker.java:59)
```

**Comment by KrystilizeNevaDies** [comment]
Please give us more information so we can reproduce this ourselves to fix it. Until that happens, this will be low priority.

**Comment by einfachBlu** [comment]
I dont know. This happens somewhere, you can see the line where it occurs. It only appears sometimes not everytime.
