### ISSUE TITLE
getNearbyEntities() NPE

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#1588]
```
java.lang.NullPointerException: Cannot invoke "net.minestom.server.coordinate.Point.x()" because "point" is null
        at net.minestom.server.coordinate.Point.distanceSquared(Point.java:202)
        at net.minestom.server.instance.EntityTrackerImpl.lambda$nearbyEntities$5(EntityTrackerImpl.java:157)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at net.minestom.server.instance.EntityTrackerImpl.lambda$nearbyEntities$6(EntityTrackerImpl.java:155)
        at net.minestom.server.utils.chunk.ChunkUtils.forChunksInRange(ChunkUtils.java:175)
        at net.minestom.server.utils.chunk.ChunkUtils.forChunksInRange(ChunkUtils.java:181)
        at net.minestom.server.instance.EntityTrackerImpl.nearbyEntities(EntityTrackerImpl.java:152)
        at net.minestom.server.instance.Instance.getNearbyEntities(Instance.java:528)
        at com.nexitcraft.server.npc.entity.ai.goal.LookCloseGoal.shouldStart(LookCloseGoal.java:37)
        at net.minestom.server.entity.ai.EntityAIGroup.tick(EntityAIGroup.java:82)
        at net.minestom.server.entity.ai.EntityAI.lambda$aiTick$0(EntityAI.java:48)
        at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
        at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
        at net.minestom.server.entity.ai.EntityAI.aiTick(EntityAI.java:48)
        at net.minestom.server.entity.EntityCreature.update(EntityCreature.java:48)
        at net.minestom.server.entity.Entity.tick(Entity.java:541)
        at net.minestom.server.thread.TickThread.tick(TickThread.java:66)
        at net.minestom.server.thread.TickThread.run(TickThread.java:41)
```

**Comment by KrystilizeNevaDies** [comment]
Please give us more information so we can reproduce this ourselves to fix it. Until that happens, this will be low priority.

**Comment by einfachBlu** [comment]
Doesn't happen every time, i dont know in which case it happen. It happens with the Method getNearbyEntities(). If i see it correctly, the chunks are loaded but could be caused because the chunk is not loaded somehow?
