### ISSUE TITLE
java.util.zip.DataFormatException: Negative payload length -1

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#1589]
```
java.util.zip.DataFormatException: Negative payload length -1
        at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:211)
        at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:103)
        at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:79)
        at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:294)
        at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:195)
        at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:135)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:161)
        at net.minestom.server.network.socket.Worker.run(Worker.java:59)
```

**Comment by KrystilizeNevaDies** [comment]
Please give us more information so we can reproduce this ourselves to fix it. Until that happens, this will be low priority.

**Comment by einfachBlu** [comment]
I dont know. This happens somewhere, you can see the line where it occurs. It only appears sometimes not everytime. iirc it appeared after the Player joined and left after a second
