### ISSUE TITLE
java.util.zip.DataFormatException: incorrect header check

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#1590]
```
java.util.zip.DataFormatException: incorrect header check
        at java.base/java.util.zip.Inflater.inflateBufferBuffer(Native Method)
        at java.base/java.util.zip.Inflater.inflate(Inflater.java:546)
        at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:222)
        at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:103)
        at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:79)
        at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:294)
        at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:195)
        at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:135)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:161)
        at net.minestom.server.network.socket.Worker.run(Worker.java:59)
```

**Comment by KrystilizeNevaDies** [comment]
Please give us more information so we can reproduce this ourselves to fix it. Until that happens, this will be low priority.

**Comment by einfachBlu** [comment]
I dont know. This happens somewhere, you can see the line where it occurs. It only appears sometimes not everytime. Also appeared on Player join & leave, not exactly sure where

**Comment by KrystilizeNevaDies** [comment]
> I dont know. This happens somewhere, you can see the line where it occurs. It only appears sometimes not everytime. Also appeared on Player join & leave, not exactly sure where

Could you create a minimal server and test if it happens there? We need a way to reproduce it ourselves.

**Comment by TheMode** [comment]
Whatever it was, the `next` branch reworked the networking code and should be more reliable.

Feel free to re-open if still relevant then
