### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Range [3, 3 + 19) out of bounds for length 3

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#1597]
```
java.lang.IndexOutOfBoundsException: Range [3, 3 + 19) out of bounds for length 3
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
        at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:361)
        at java.base/java.util.Objects.checkFromIndexSize(Objects.java:411)
        at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:874)
        at java.base/java.nio.ByteBuffer.get(ByteBuffer.java:910)
        at net.minestom.server.network.NetworkBufferTypes.lambda$static$23(NetworkBufferTypes.java:218)
        at net.minestom.server.network.NetworkBuffer.read(NetworkBuffer.java:101)
        at net.minestom.server.network.packet.client.handshake.HandshakePacket.<init>(HandshakePacket.java:51)
        at net.minestom.server.network.PacketProcessor.create(PacketProcessor.java:37)
        at net.minestom.server.network.PacketProcessor.process(PacketProcessor.java:45)
        at net.minestom.server.network.player.PlayerSocketConnection.lambda$processPackets$0(PlayerSocketConnection.java:109)
        at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:230)
        at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:103)
        at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:79)
        at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:294)
        at java.base/sun.nio.ch.EPollSelectorImpl.processEvents(EPollSelectorImpl.java:195)
        at java.base/sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:135)
        at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
        at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:161)
        at net.minestom.server.network.socket.Worker.run(Worker.java:59)
```

**Comment by Distractic** [comment]
Can you give us a context ?
- code
- Minestom version
- Player version
Etc.

**Comment by KrystilizeNevaDies** [comment]
Please give us more information so we can reproduce this ourselves to fix it. Until that happens, this will be low priority.

**Comment by einfachBlu** [comment]
Minestom newest Version. 1.19.2 Badlion Client, also came with Vanilla 1.19.2. There is no code that causes this (not from my side) so something internal

**Comment by KrystilizeNevaDies** [comment]
So you have no code? Could you write a minimal server with strips for us to reproduce the error?

**Comment by TheMeinerLP** [comment]
@einfachBlu Can you please provide some code to reproduce it ?
If it not longer a issue please close it.

**Comment by kermandev** [comment]
Minestoms networking has been refactored since this issue, if it still persists, please open a new one; Likely a invalid handshake packet of a bot scanning your server.

**Comment by einfachBlu** [comment]
too long ago but yes, probably fixed, never experienced that exception again recently
