### ISSUE TITLE
Swapping item in creative mode inventory throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by xbendan** [Minestom/Minestom#1726]
`java.lang.ArrayIndexOutOfBoundsException: Index 76 out of bounds for length 46
        at java.base/jdk.internal.util.Preconditions$2.apply(Preconditions.java:63)
        at java.base/jdk.internal.util.Preconditions$2.apply(Preconditions.java:60)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.lang.invoke.VarHandleReferences$Array.getVolatile(VarHandleReferences.java:602)
        at net.minestom.server.inventory.AbstractInventory.getItemStack(AbstractInventory.java:185)
        at net.minestom.server.listener.CreativeInventoryActionListener.listener(CreativeInventoryActionListener.java:24)
        at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:90)
        at net.minestom.server.entity.Player.lambda$interpretPacketQueue$13(Player.java:1746)
        at org.jctools.queues.MpscUnboundedXaddArrayQueue.drain(MpscUnboundedXaddArrayQueue.java:312)
        at net.minestom.server.entity.Player.interpretPacketQueue(Player.java:1746)
        at net.minestom.server.entity.Player.update(Player.java:329)
        at net.minestom.server.entity.Entity.tick(Entity.java:537)
        at net.minestom.server.thread.TickThread.tick(TickThread.java:66)
        at net.minestom.server.thread.TickThread.run(TickThread.java:41)`

This happens when you try to use [F] to swap item in the creative mode inventory (any tabs except Survival Inventory), but it does swap correctly, just an exception will be thrown in the console.

How to:
- Switch to creative mode
- Open your inventory
- Go to any tab except Survival Inventory
- Put your mouse cursor in the bottom grids (1-9 item slots)
- Press F (or the key you set to swap items from main hand to off hand)

**Comment by GreatWyrm** [comment]
I've figured out why this happens

I'm almost certain it's a base minecraft bug. So this is caused by these lines in CreativeInventoryScreen:
```
j = 45 + button;
if (actionType == SlotActionType.SWAP) {
     this.client.interactionManager.clickCreativeStack(itemStack, j - ((CreativeScreenHandler)this.handler).slots.size() + 9 + 36);
```

When you offhand swap, button is set to 40, so the result is 85 - (slots.size()) + 45, and slots.size() always seems to be 54, resulting in 76.

Thing is, the vanilla server does bounds checking on this packet, so the packet with slot number 76 is just discarded.
Proper solution is just to do some bound checking on Minestom's side (probably a good thing to implement in case someone tries sending some bad packets).
