### ISSUE TITLE
Index out of bounds when calling FlexiblePalette#retrieveAll()

### ISSUE THREAD

**Issue by Tofaa2** [Minestom/Minestom#1743]
Full stacktrace:
```
[ForkJoinPool.commonPool-worker-1] [04:02:25] (EncryptionResponsePacket.lambda$process$4) - INFO - UUID of player Tofaa is b6bd953d-f87e-4be2-a308-777861b54d37        
> java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
        at net.minestom.server.instance.palette.FlexiblePalette.retrieveAll(FlexiblePalette.java:243)
        at net.minestom.server.instance.palette.FlexiblePalette.getAll(FlexiblePalette.java:66)
        at net.minestom.server.instance.palette.AdaptivePalette.optimizedPalette(AdaptivePalette.java:124)
        at net.minestom.server.instance.palette.AdaptivePalette.write(AdaptivePalette.java:110)
        at net.minestom.server.network.NetworkBuffer.write(NetworkBuffer.java:96)
        at net.minestom.server.instance.Section.write(Section.java:68)
        at net.minestom.server.network.NetworkBuffer.write(NetworkBuffer.java:96)
        at net.minestom.server.instance.DynamicChunk.lambda$createChunkPacket$2(DynamicChunk.java:208)
        at net.minestom.server.network.NetworkBuffer.makeArray(NetworkBuffer.java:278)
        at net.minestom.server.instance.DynamicChunk.lambda$createChunkPacket$3(DynamicChunk.java:207)
        at net.minestom.server.utils.ObjectPool.use(ObjectPool.java:85)
        at net.minestom.server.instance.DynamicChunk.createChunkPacket(DynamicChunk.java:206)
        at net.minestom.server.network.packet.server.CachedPacket.updatedCache(CachedPacket.java:52)
        at net.minestom.server.network.packet.server.CachedPacket.body(CachedPacket.java:42)
        at net.minestom.server.network.player.PlayerSocketConnection.writePacketSync(PlayerSocketConnection.java:353)
        at net.minestom.server.network.player.PlayerSocketConnection.lambda$sendPacket$1(PlayerSocketConnection.java:160)
        at org.jctools.queues.MessagePassingQueueUtil.drain(MessagePassingQueueUtil.java:53)
        at org.jctools.queues.MpUnboundedXaddArrayQueue.drain(MpUnboundedXaddArrayQueue.java:435)
        at org.jctools.queues.MpscUnboundedXaddArrayQueue.drain(MpscUnboundedXaddArrayQueue.java:28)
        at net.minestom.server.network.socket.Worker.run(Worker.java:46)
```

Happens when calling something silly like

```java
            MinecraftServer.getSchedulerManager().buildTask(() -> {
                Polaroid.getDefaultInstance().saveInstance().thenRun(Polaroid.getDefaultInstance()::saveChunksToStorage).thenRun(() -> {
                    Polaroid.getLogger().info("Saved instance");
                });
            }).delay(Duration.ofSeconds(10)).schedule();
```

Code used is simply a wrapper around minestom + stacktrace doesnt really show my code in it. But still https://github.com/Polar-Network

**Comment by kermandev** [comment]
Palettes and networking have been completely refactored since this was reported, please open a new issue or let me know if this continues to be a problem.
