### ISSUE TITLE
Bug: not sending passenger information correctly upon join

### ISSUE THREAD

**Issue by MrDienns** [Minestom/Minestom#1750]
Spawning an entity upon startup, giving said entity passengers, and then joining the server, seems to not be sent to the client correctly.

See discussion here; https://github.com/Minestom/Minestom/discussions/1749#discussioncomment-5010627

Using version `-SNAPSHOT` from Jitpack.

```xml
            <dependency>
                <groupId>com.github.Minestom</groupId>
                <artifactId>Minestom</artifactId>
                <version>-SNAPSHOT</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.jboss.shrinkwrap.resolver</groupId>
                        <artifactId>shrinkwrap-resolver-depchain</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

**Comment by TheMeinerLP** [comment]
Same behaviour but different result:
```
22:50:08.027 [main] WARN net.minestom.server.instance.EntityTrackerImpl - Attempted to move unregistered entity 2 in the entity tracker
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "net.minestom.server.instance.Chunk.getChunkX()" because "this.currentChunk" is null
        at net.minestom.server.entity.Entity.refreshCoordinate(Entity.java:1346)
        at net.minestom.server.entity.Entity.updatePassengerPosition(Entity.java:1320)
        at net.minestom.server.entity.Entity.addPassenger(Entity.java:973)
        at net.minestom.demo.bugs.PassengerEntityIsNotSentToClient.spawnPassangerEntity(PassengerEntityIsNotSentToClient.java:22)
        at net.minestom.demo.Main.main(Main.java:141)
```

Code for replication:
```
public final class PassengerEntityIsNotSentToClient {

    public static void spawnPassangerEntity() {
        var instances = MinecraftServer.getInstanceManager().getInstances();
        Instance instance = instances.stream().skip(new Random().nextInt(instances.size())).findFirst().orElse(null);
        Entity entity = new Entity(EntityType.BEE);
        Entity passenger = new Entity(EntityType.ZOMBIE);
        entity.setInstance(instance, new Pos(0, 42, 0));
        passenger.setInstance(instance,new Pos(0, 42, 0));
        entity.spawn();
        passenger.spawn();
        entity.addPassenger(passenger);
    }

}
```

**Comment by emortaldev** [comment]
Still an issue, managed to fix it for my use case by extending Entity and using
```java
@Override
public void updateNewViewer(Player player) {
    super.updateNewViewer(player);
    sendPacketToViewers(getPassengersPacket());
}
```
