### ISSUE TITLE
Dimension issue when creating FakePlayer

### ISSUE THREAD

**Issue by Tofaa2** [Minestom/Minestom#1776]
Code:
https://hastebin.com/share/afawalapes.java

Stacktrace:
> java.lang.IllegalArgumentException: The dimension needs to be different than the current one!
	at net.minestom.server.utils.validate.Check.argCondition(Check.java:36)
	at net.minestom.server.entity.Player.sendDimension(Player.java:1341)
	at net.minestom.server.entity.Player.spawnPlayer(Player.java:654)
	at net.minestom.server.entity.Player.lambda$setInstance$8(Player.java:573)
	at net.minestom.server.entity.Player.lambda$setInstance$11(Player.java:612)
	at net.minestom.server.timer.Task$Builder$1.get(Task.java:68)
	at net.minestom.server.timer.Task$Builder$1.get(Task.java:59)
	at net.minestom.server.timer.SchedulerImpl.handleTask(SchedulerImpl.java:92)
	at net.minestom.server.timer.SchedulerImpl.lambda$processTick$3(SchedulerImpl.java:56)
	at org.jctools.queues.MessagePassingQueueUtil.drain(MessagePassingQueueUtil.java:39)
	at org.jctools.queues.BaseMpscLinkedArrayQueue.drain(BaseMpscLinkedArrayQueue.java:612)
	at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:23)
	at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:63)
	at net.minestom.server.timer.SchedulerImpl.processTick(SchedulerImpl.java:53)
	at net.minestom.server.timer.SchedulerImpl.processTick(SchedulerImpl.java:39)
	at net.minestom.server.timer.SchedulerManager.processTick(SchedulerManager.java:19)
	at net.minestom.server.ServerProcessImpl$TickerImpl.tick(ServerProcessImpl.java:280)
	at net.minestom.server.thread.TickSchedulerThread.run(TickSchedulerThread.java:24)

Happens when calling setInstance i think

**Comment by ZakShearman** [comment]
Please post the code in here. Using hastebin makes it expire

**Comment by dev-hydrogen** [comment]
yeah the code has already expired
