### ISSUE TITLE
ExtensionClassLoader Issue

### ISSUE THREAD

**Issue by GreyLake** [Minestom/Minestom#1825]
Hello, I'm having issues with Extensions and Extension Dependencies. 

In my instance, I have a bearbone server, with two simple Extensions, where one of the Extensions depends on the other. Lets call these extension A and extension B where B depends on A.

When simply stopping the server, the main process attemps to unload dependencies. First it unloads A, and knowing that B depends on A, it attemps to unload B. This is the first of many issues. Doing the above, results in a ExtensionClassLoader Issue which can be demonstated below.

```
[main] [14:17:23] (ServerProcessImpl.start) - INFO - Minestom server started successfully.
[Thread-1] [14:17:27] (ServerProcessImpl.stop) - INFO - Stopping Minestom server.
[Thread-1] [14:17:27] (ServerProcessImpl.stop) - INFO - Unloading all extensions.
[Thread-1] [14:17:27] (ExtensionManager.unloadExtension) - INFO - Unloading dependent extension B (because it depends on A)
> Exception in thread "Thread-1" java.lang.IllegalStateException: Extension class loader is not an ExtensionClassLoader
	at net.minestom.server.extensions.Extension.getExtensionClassLoader(Extension.java:53)
	at net.minestom.server.extensions.ExtensionManager.unload(ExtensionManager.java:688)
	at net.minestom.server.extensions.ExtensionManager.unloadExtension(ExtensionManager.java:676)
	at net.minestom.server.extensions.ExtensionManager.shutdown(ExtensionManager.java:658)
	at net.minestom.server.ServerProcessImpl.stop(ServerProcessImpl.java:246)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

This issue isn't caused by the code within extension A and B. These extensions are also barebone and contain any code.

Another issue occures when attempting to call a super instance within any of the extensions. This also throws a ExtensionClassLoader Error. Let's try by calling "this.getDataDirectory();" within one of the extension classes. (yes I am aware that there are other ways to obtain DataDirectory, like "MinecraftServer.getExtensionManager().getExtensionDataRoot();")

The above is called as follows:

```
public class A extends Extension {
    @Override
    public void initialize(){
            this.getDataDirectory();
    }
    
    @Override
    public void terminate() {
    }
}
```

This throws the following:

```
[main] [14:29:03] (ServerProcessImpl.start) - INFO - Starting Minestom server.

Exception in thread "main" java.lang.IllegalStateException: Extension class loader is not an ExtensionClassLoader
	at net.minestom.server.extensions.Extension.getExtensionClassLoader(Extension.java:53)
	at net.minestom.server.extensions.Extension.getOrigin(Extension.java:58)
	at net.minestom.server.extensions.Extension.getDataDirectory(Extension.java:76)
	at ml.blitzcraft.smash.Smash.initialize(A.java:5)
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:647)
	at net.minestom.server.extensions.ExtensionManager.gotoInit(ExtensionManager.java:127)
	at net.minestom.server.ServerProcessImpl.start(ServerProcessImpl.java:216)
	at net.minestom.server.MinecraftServer.start(MinecraftServer.java:322)
	at net.minestom.server.MinecraftServer.start(MinecraftServer.java:327)
	at ml.blitzcraft.server.Server.main(Server.java:21)
```

Now of course, this can be avoided by not calling any Extension related code from the child class. However, there is still the original issue pointed our where the default server implmentation itself causes the error with how it unloads extensions automatically. I would have much prefered to have a way to manually unload extensions - However this isn't posible with the current visibility of the ExtensionManagers Classes. Am I missing an implementations somewhere? Is there some proprietary code that I need to include to rid of these? Bootstraping was removed long ago and replaced with the ExtensionClassLoader which has only been causing issues.

I will include the code below for the server errors when simply stopping the server here:
```
public static void main(String[] args) {

        MinecraftServer server = MinecraftServer.init();

        MinecraftServer.getGlobalEventHandler().addListener(PlayerLoginEvent.class, event -> {
            if (MinecraftServer.getInstanceManager().getInstances().isEmpty())
                event.getPlayer().kick(Component.text("There is no instance available!", NamedTextColor.RED));
        });

        server.start("127.0.0.1", 25565);
 }
```

That's it, that's the code, it's essentially the code provided by the Wiki but boiled down a bit. As for the extensions themselves, They are all properly configured, a simple A and B class are created with B needing a dependency of A. These extensions are compiled down into a JAR, which only has the extensions compiled code + extension.JSON. I hope we can discuss this issue further and figure out a solution. This occures on the latest release (master) of minestom.

**Comment by GreyLake** [comment]
Alrighty! So, I did a lot more digging. There are a few things to consider. When attempting to test extensions, it's crucial that the server is a jar file. You (sadly) cannot test your extensions Jars through server classes. You must compile down the server into a jar file. This resolves the issues regarding the ExtensionClassLoader.
