### ISSUE TITLE
Cauldron has missing level propery

### ISSUE THREAD

**Issue by titivermeesch** [Minestom/Minestom#2110]
I was testing a few different region files that I could load with `AnvilLoader`, and one of the them made this issue appear.
The world I downloaded was this one: https://www.planetminecraft.com/project/small-server-hub-lobby-free-download/

The error is the following:
```
java.lang.IllegalArgumentException: Property level is not valid for block minecraft:cauldron{properties={}, nbt=null, handler=null}
        at net.minestom.server.instance.block.BlockImpl.findKeyIndex(BlockImpl.java:222)
        at net.minestom.server.instance.block.BlockImpl.withProperties(BlockImpl.java:138)
        at net.minestom.server.instance.AnvilLoader.loadSections(AnvilLoader.java:248)
        at net.minestom.server.instance.AnvilLoader.loadMCA(AnvilLoader.java:125)
        at net.minestom.server.instance.AnvilLoader.loadChunk(AnvilLoader.java:86)
        at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$6(InstanceContainer.java:294)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

The world still loads in except chunks where cauldrons are present.

My `AnvilLoader` usage is very simple:

```java
InstanceManager instanceManager = MinecraftServer.getInstanceManager();
InstanceContainer instanceContainer = instanceManager.createInstanceContainer();
instanceContainer.setChunkLoader(new AnvilLoader("worlds/world"));
```

**Comment by titivermeesch** [comment]
I am currently trying to debug the source code and see if I can find the issue myself

**Comment by titivermeesch** [comment]
I saw a discussion on Discord talking about this exact same issue. Is this something that should/can be fixed? Or are the region files I'm using simply not compatible with 1.20.4

**Comment by mworzala** [comment]
Cauldron does not have a level property. There is now water cauldron and lava cauldron. You should update the region using the vanilla server, Minestom does not provide game data upgrades.
