### ISSUE TITLE
Using switchEntityType on a Player causes a ClassCastException when trying to damage them

### ISSUE THREAD

**Issue by GreatWyrm** [Minestom/Minestom#2152]
When trying to use the [switchEntityType](https://javadoc.minestom.net/net/minestom/server/entity/Entity.html#switchEntityType(net.minestom.server.entity.EntityType)) method, it works fine to change a player's model to another mob, but will fail when trying to apply damage to them. The error I encountered was here:

```
java.lang.ClassCastException: class net.minestom.server.entity.metadata.monster.zombie.ZombieMeta cannot be cast to class net.minestom.server.entity.metadata.PlayerMeta (net.minestom.server.entity.metadata.monster.zombie.ZombieMeta and net.minestom.server.entity.metadata.PlayerMeta are in unnamed module of loader 'app')
	at net.minestom.server.entity.Player.getPlayerMeta(Player.java:1040)
	at net.minestom.server.entity.Player.getAdditionalHearts(Player.java:1052)
	at net.minestom.server.entity.LivingEntity.lambda$damage$3(LivingEntity.java:344)
	at net.minestom.server.event.EventNode.callCancellable(EventNode.java:217)
	at net.minestom.server.event.EventDispatcher.callCancellable(EventDispatcher.java:18)
	at net.minestom.server.entity.LivingEntity.damage(LivingEntity.java:332)
```

**Comment by GreatWyrm** [comment]
Side note: This also happens with any other action that requires modifying the player meta (like if the player changes client settings, etc)

**Comment by N4TH4NOT** [comment]
Also happen when the player break a block.

`java.lang.ClassCastException:` class net.minecraft.world.entity.item.FallingBlockEntity cannot be cast to class net.minecraft.world.entity.LivingEntity (net.minecraft.world.entity.item.FallingBlockEntity and net.minecraft.world.entity.LivingEntity are in unnamed module of loader 'knot' @4c6e276e)`

**Comment by N4TH4NOT** [comment]
Also happen when the player break a block.

Client crash log:
```
java.lang.ClassCastException:` class net.minecraft.world.entity.item.FallingBlockEntity cannot be cast to class net.minecraft.world.entity.LivingEntity (net.minecraft.world.entity.item.FallingBlockEntity and net.minecraft.world.entity.LivingEntity are in unnamed module of loader 'knot' @4c6e276e)
		at net.minecraft.client.multiplayer.ClientPacketListener.handleAnimate(ClientPacketListener.java:1105) ~[client-intermediary.jar:?]
	at net.minecraft.network.protocol.game.ClientboundAnimatePacket.handle(ClientboundAnimatePacket.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.network.protocol.game.ClientboundAnimatePacket.handle(ClientboundAnimatePacket.java:10) ~[client-intermediary.jar:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:164) [client-intermediary.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) [client-intermediary.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:138) [client-intermediary.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:123) [client-intermediary.jar:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1318) [client-intermediary.jar:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:947) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) [client-intermediary.jar:?]
```
