### ISSUE TITLE
Kick with reason: Network Protocol Error

### ISSUE THREAD

**Issue by Z3koR** [Minestom/Minestom#2169]
When I join to my server, I get the message `Network Protocol Error'. I thought there was a problem with my server, but I created an empty project and the error remained.

I use `1_20_5-ce92c7ccde` minestom version.

There are many similar errors in the **minecraft** console. Here is one of them:
```
>> Errors in element minecraft:wooded_badlands:
java.lang.IllegalStateException: Failed to parse local data
	at ala.a(SourceFile:271)
	at ala$a.a(SourceFile:92)
	at ala.a(SourceFile:140)
	at ala.a(SourceFile:149)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at ala.a(SourceFile:149)
	at ala.a(SourceFile:140)
	at fyj$a.a(SourceFile:49)
	at fyj.a(SourceFile:59)
	at fxu.a(SourceFile:117)
	at fxu.a(SourceFile:109)
	at fxu.a(SourceFile:117)
	at abr.a(SourceFile:22)
	at abr.a(SourceFile:8)
	at zz.a(SourceFile:25)
	at bpl.d(SourceFile:162)
	at bpp.d(SourceFile:23)
	at bpl.A(SourceFile:136)
	at bpl.bA(SourceFile:121)
	at ffg.c(SourceFile:1275)
	at ffg.f(SourceFile:888)
	at net.minecraft.client.main.Main.main(SourceFile:265)
Caused by: java.io.FileNotFoundException: minecraft:worldgen/biome/wooded_badlands.json
	at aus.b(SourceFile:23)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at aus.getResourceOrThrow(SourceFile:23)
	at ala.a(SourceFile:268)
	... 21 more
```

At the end:
```
[Render thread/ERROR]: Failed to handle packet abr@3d2e3eae
java.lang.IllegalStateException: Failed to load registries due to above errors
	at ala.a(SourceFile:162)
	at ala.a(SourceFile:140)
	at fyj$a.a(SourceFile:49)
	at fyj.a(SourceFile:59)
	at fxu.a(SourceFile:117)
	at fxu.a(SourceFile:109)
	at fxu.a(SourceFile:117)
	at abr.a(SourceFile:22)
	at abr.a(SourceFile:8)
	at zz.a(SourceFile:25)
	at bpl.d(SourceFile:162)
	at bpp.d(SourceFile:23)
	at bpl.A(SourceFile:136)
	at bpl.bA(SourceFile:121)
	at ffg.c(SourceFile:1275)
	at ffg.f(SourceFile:888)
	at net.minecraft.client.main.Main.main(SourceFile:265)
```

**Comment by cosrnic** [comment]
Try using the latest for 1.20.5 [`1_20_5-d911dab9dd`]

**Comment by Z3koR** [comment]
> Try using the latest for 1.20.5 [`1_20_5-d911dab9dd`]

No, it's still a error. Don't you have this error?

**Comment by cosrnic** [comment]
No I dont have this error at all, what does your server code look like?

**Comment by Z3koR** [comment]
> No I dont have this error at all, what does your server code look like?

The code of the new project:
```
import net.minestom.server.MinecraftServer
import net.minestom.server.coordinate.Pos
import net.minestom.server.event.player.AsyncPlayerConfigurationEvent
import net.minestom.server.instance.block.Block

fun main() {
    val server = MinecraftServer.init()

    val instanceManager = MinecraftServer.getInstanceManager()

    val instance = instanceManager.createInstanceContainer().apply {
        setGenerator {
            it.modifier().fillHeight(0, 1, Block.GRASS_BLOCK)
        }
    }

    MinecraftServer.getGlobalEventHandler().addListener(AsyncPlayerConfigurationEvent::class.java) {
        it.spawningInstance = instance
        it.player.respawnPoint = Pos(0.5, 1.0, 0.5)
    }

    println("Starting server...")
    server.start("localhost", 25565)
    println("Server started!")
}
```

**Comment by MelonHell** [comment]
Sometimes some players cannot connect to my server, also with the error "Network Protocol Error". One of the players was able to solve the problem by joining from another launcher

**Comment by Z3koR** [comment]
I try another launcher but It didn't help(

**Comment by Z3koR** [comment]
I do not know why, but when I went from version below 1.20.5, it was written in the list of servers that the server has version 1.20.6. In the end, I logged into the server with version 1.20.6 and I was not kicked out. 0.o

**Comment by Z3koR** [comment]
I do not know why, but when I went from version below 1.20.5, it was written in the list of servers that the server has version 1.20.6. In the end, I logged into the server with version 1.20.6 and I was not kicked out. 0.o

**Comment by DZultra** [comment]
Hi,
on the server I play on the version is the problem. We dont use Minestorm but many other plugins.
People who use 1.20.5/6 or 1.21.1 sometimes get the "Network Protocol Error". We fixed it for them by using 1.20.1/2/4

**Comment by TheMeinerLP** [comment]
@Z3koR Can you provide some code of reproduce ?
