### ISSUE TITLE
Bug: `ArrayIndexOutOfBoundsException` when loading some chunks

### ISSUE THREAD

**Issue by GoodLucky777** [Minestom/Minestom#2180]
# Info
Version: b3aa996e1df40991c241769f571550d2adbebf38

# How to reproduce
1. Download this Minecraft `1.20.6` world. ([example-world.zip](https://github.com/user-attachments/files/15751483/example-world.zip))
2. Load the world with default `AnvilLoader`.
3. If you connect to the server, these errors will be occurred.
```
java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 5
	at net.minestom.server.instance.anvil.AnvilLoader.lambda$loadSections$2(AnvilLoader.java:198)
	at net.minestom.server.instance.palette.FlexiblePalette.setAll(FlexiblePalette.java:123)
	at net.minestom.server.instance.palette.AdaptivePalette.setAll(AdaptivePalette.java:60)
	at net.minestom.server.instance.anvil.AnvilLoader.loadSections(AnvilLoader.java:196)
	at net.minestom.server.instance.anvil.AnvilLoader.loadMCA(AnvilLoader.java:113)
	at net.minestom.server.instance.anvil.AnvilLoader.loadChunk(AnvilLoader.java:89)
	at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$7(InstanceContainer.java:305)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```
4. These chunk will not be loaded. (All blocks are `minecraft:air`)

**Comment by GoodLucky777** [comment]
There was no error before 1.20.6 update. (19bb74e94265839f20f87161e41e5810463eb5b1)

**Comment by mworzala** [comment]
Fixed in https://github.com/Minestom/Minestom/commit/aca4c3db5e9337f645ba21bb1959bfab29fe9327
