### ISSUE TITLE
Bug: Handshake packet reading?

### ISSUE THREAD

**Issue by Tofaa2** [Minestom/Minestom#2241]
Me and @[GoldenCookieGIT ](https://github.com/GoldenCookieGIT) are working on a minestom project, but occasionally stuff like this in the handshake state (during server list ping handshaking) we get console errors

![image](https://github.com/Minestom/Minestom/assets/82680183/d8550cbb-5d6c-4938-bf09-8de795433dcb)

At first it seems like invalid packet sent, but im not sure. Has anyone come across this? And possibly make it not throw an error but just lightly log the information

**Comment by hapily04** [comment]
I usually get errors like these as well overnight

**Comment by Tofaa2** [comment]
> overnight

our best guess is bot scrapers

**Comment by cosrnic** [comment]
Might be related to this but im able to consistently get
```
java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer$1.apply(Buffer.java:757)
	at java.base/java.nio.Buffer$1.apply(Buffer.java:754)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:768)
	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:358)
	at net.minestom.server.network.NetworkBufferTypeImpl$VarIntType.read(NetworkBufferTypeImpl.java:214)
	at net.minestom.server.network.NetworkBufferTypeImpl$VarIntType.read(NetworkBufferTypeImpl.java:172)
	at net.minestom.server.network.NetworkBuffer.read(NetworkBuffer.java:126)
	at net.minestom.server.network.NetworkBufferTypeImpl$StringType.read(NetworkBufferTypeImpl.java:291)
	at net.minestom.server.network.NetworkBufferTypeImpl$StringType.read(NetworkBufferTypeImpl.java:281)
	at net.minestom.server.network.NetworkBuffer.read(NetworkBuffer.java:126)
	at net.minestom.server.network.packet.client.handshake.ClientHandshakePacket.<init>(ClientHandshakePacket.java:20)
	at net.minestom.server.network.PacketProcessor.create(PacketProcessor.java:41)
	at net.minestom.server.network.PacketProcessor.process(PacketProcessor.java:53)
	at net.minestom.server.network.player.PlayerSocketConnection.lambda$processPackets$0(PlayerSocketConnection.java:103)
	at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:231)
	at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:97)
	at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:103)
	at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:297)
	at java.base/sun.nio.ch.WEPollSelectorImpl.processEvents(WEPollSelectorImpl.java:186)
	at java.base/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:122)
	at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
	at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:168)
	at net.minestom.server.network.socket.Worker.run(Worker.java:83)
15:25:44.174 [Ms-worker-4] WARN net.minestom.server.network.player.PlayerSocketConnection -- WARNING: Packet (HANDSHAKE) 0x4e not fully read (java.nio.DirectByteBuffer[pos=1 lim=2 cap=2]) null
java.lang.IllegalArgumentException: Unknown connection intent: 115
	at net.minestom.server.network.packet.client.handshake.ClientHandshakePacket$Intent.fromId(ClientHandshakePacket.java:54)
	at net.minestom.server.network.packet.client.handshake.ClientHandshakePacket.<init>(ClientHandshakePacket.java:23)
	at net.minestom.server.network.PacketProcessor.create(PacketProcessor.java:41)
	at net.minestom.server.network.PacketProcessor.process(PacketProcessor.java:53)
	at net.minestom.server.network.player.PlayerSocketConnection.lambda$processPackets$0(PlayerSocketConnection.java:103)
	at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:231)
	at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:97)
	at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:103)
	at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:297)
	at java.base/sun.nio.ch.WEPollSelectorImpl.processEvents(WEPollSelectorImpl.java:186)
	at java.base/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:122)
	at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
	at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:168)
	at net.minestom.server.network.socket.Worker.run(Worker.java:83)
15:25:44.175 [Ms-worker-4] WARN net.minestom.server.network.player.PlayerSocketConnection -- WARNING: Packet (HANDSHAKE) 0x0 not fully read (java.nio.DirectByteBuffer[pos=1 lim=7 cap=7]) null
```
when trying to join a minestom 1.21 server on minecraft 1.6.4 [ik this seems stupid but im guessing there are bots that attempt to join servers on a version before 1.7]. The serverlist information also does not work for versions below 1.7 [just shows `Can't reach server`]

**Comment by Tofaa2** [comment]
> Might be related to this but im able to consistently get
> 
> ```
> java.lang.IndexOutOfBoundsException
> 	at java.base/java.nio.Buffer$1.apply(Buffer.java:757)
> 	at java.base/java.nio.Buffer$1.apply(Buffer.java:754)
> 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
> 	at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
> 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
> 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
> 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
> 	at java.base/java.nio.Buffer.checkIndex(Buffer.java:768)
> 	at java.base/java.nio.DirectByteBuffer.get(DirectByteBuffer.java:358)
> 	at net.minestom.server.network.NetworkBufferTypeImpl$VarIntType.read(NetworkBufferTypeImpl.java:214)
> 	at net.minestom.server.network.NetworkBufferTypeImpl$VarIntType.read(NetworkBufferTypeImpl.java:172)
> 	at net.minestom.server.network.NetworkBuffer.read(NetworkBuffer.java:126)
> 	at net.minestom.server.network.NetworkBufferTypeImpl$StringType.read(NetworkBufferTypeImpl.java:291)
> 	at net.minestom.server.network.NetworkBufferTypeImpl$StringType.read(NetworkBufferTypeImpl.java:281)
> 	at net.minestom.server.network.NetworkBuffer.read(NetworkBuffer.java:126)
> 	at net.minestom.server.network.packet.client.handshake.ClientHandshakePacket.<init>(ClientHandshakePacket.java:20)
> 	at net.minestom.server.network.PacketProcessor.create(PacketProcessor.java:41)
> 	at net.minestom.server.network.PacketProcessor.process(PacketProcessor.java:53)
> 	at net.minestom.server.network.player.PlayerSocketConnection.lambda$processPackets$0(PlayerSocketConnection.java:103)
> 	at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:231)
> 	at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:97)
> 	at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:103)
> 	at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:297)
> 	at java.base/sun.nio.ch.WEPollSelectorImpl.processEvents(WEPollSelectorImpl.java:186)
> 	at java.base/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:122)
> 	at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
> 	at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:168)
> 	at net.minestom.server.network.socket.Worker.run(Worker.java:83)
> 15:25:44.174 [Ms-worker-4] WARN net.minestom.server.network.player.PlayerSocketConnection -- WARNING: Packet (HANDSHAKE) 0x4e not fully read (java.nio.DirectByteBuffer[pos=1 lim=2 cap=2]) null
> java.lang.IllegalArgumentException: Unknown connection intent: 115
> 	at net.minestom.server.network.packet.client.handshake.ClientHandshakePacket$Intent.fromId(ClientHandshakePacket.java:54)
> 	at net.minestom.server.network.packet.client.handshake.ClientHandshakePacket.<init>(ClientHandshakePacket.java:23)
> 	at net.minestom.server.network.PacketProcessor.create(PacketProcessor.java:41)
> 	at net.minestom.server.network.PacketProcessor.process(PacketProcessor.java:53)
> 	at net.minestom.server.network.player.PlayerSocketConnection.lambda$processPackets$0(PlayerSocketConnection.java:103)
> 	at net.minestom.server.utils.PacketUtils.readPackets(PacketUtils.java:231)
> 	at net.minestom.server.network.player.PlayerSocketConnection.processPackets(PlayerSocketConnection.java:97)
> 	at net.minestom.server.network.socket.Worker.lambda$run$0(Worker.java:103)
> 	at java.base/sun.nio.ch.SelectorImpl.processReadyEvents(SelectorImpl.java:297)
> 	at java.base/sun.nio.ch.WEPollSelectorImpl.processEvents(WEPollSelectorImpl.java:186)
> 	at java.base/sun.nio.ch.WEPollSelectorImpl.doSelect(WEPollSelectorImpl.java:122)
> 	at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:130)
> 	at java.base/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:168)
> 	at net.minestom.server.network.socket.Worker.run(Worker.java:83)
> 15:25:44.175 [Ms-worker-4] WARN net.minestom.server.network.player.PlayerSocketConnection -- WARNING: Packet (HANDSHAKE) 0x0 not fully read (java.nio.DirectByteBuffer[pos=1 lim=7 cap=7]) null
> ```
> 
> when trying to join a minestom 1.21 server on minecraft 1.6.4 [ik this seems stupid but im guessing there are bots that attempt to join servers on a version before 1.7]. The serverlist information also does not work for versions below 1.7 [just shows `Can't reach server`]

seems like bots yeah, but i thought minestom had full legacy server list ping handling so i was confused

**Comment by hapily04** [comment]
> > overnight
> 
> our best guess is bot scrapers

That's what I was thinking

**Comment by TheMeinerLP** [comment]
@Tofaa2 can you provide some code of reproduce ?
