### ISSUE TITLE
Weird "invalid coordinate" error.

### ISSUE THREAD

**Issue by fenziie** [Minestom/Minestom#2339]
Here is my code:

```java
package me.zeeplockd;

import net.minestom.server.MinecraftServer;
import net.minestom.server.coordinate.Pos;
import net.minestom.server.entity.Player;
import net.minestom.server.event.GlobalEventHandler;
import net.minestom.server.event.player.AsyncPlayerConfigurationEvent;
import net.minestom.server.instance.InstanceContainer;
import net.minestom.server.instance.InstanceManager;
import net.minestom.server.instance.LightingChunk;
import net.minestom.server.instance.block.Block;

public class Main {
    public static void main(String[] args) {
        System.out.println("Hello Saturn!");

        // initialize server
        MinecraftServer server = MinecraftServer.init();

        // create instance (instance is basically just a world)
        InstanceManager instanceManager = MinecraftServer.getInstanceManager();
        InstanceContainer instanceContainer = instanceManager.createInstanceContainer();

        // generate a basic world
        instanceContainer.setGenerator(unit -> {
            unit.modifier().fillHeight(0, 5, Block.POLISHED_ANDESITE);
            unit.modifier().setBlock(0, 5, 0, Block.AMETHYST_BLOCK);
        });

        // add lighting
        instanceContainer.setChunkSupplier(LightingChunk::new);

        // add an event handler for player spawn
        GlobalEventHandler globalEventHandler = MinecraftServer.getGlobalEventHandler();
        globalEventHandler.addListener(AsyncPlayerConfigurationEvent.class, event -> {
            final Player player = event.getPlayer();
            event.setSpawningInstance(instanceContainer);
            player.setRespawnPoint(new Pos(0, 7, 0));
        });

        server.start("0.0.0.0", 25565);
    }
}
```

And here is the error:
```
java.lang.IllegalArgumentException: Invalid coordinates: 0, 5, 0 for area Vec[x=-128.0, y=-64.0, z=0.0] Vec[x=-112.0, y=320.0, z=16.0]
	at net.minestom.server.instance.generator.GeneratorImpl$AreaModifierImpl.checkBorder(GeneratorImpl.java:440)
	at net.minestom.server.instance.generator.GeneratorImpl$AreaModifierImpl.setBlock(GeneratorImpl.java:318)
	at me.zeeplockd.Main.lambda$main$0(Main.java:27)
	at net.minestom.server.instance.InstanceContainer.lambda$createChunk$10(InstanceContainer.java:356)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1403)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by fenziie** [comment]
So far all I can tell is the problem is with the line where I set a block to amethyst, but the funny thing is it works as intended on join, so the error doesnt really do anything.

**Comment by mudkipdev** [comment]
Move the setBlock line out of your generator and put it as instance.setBlock instead.

**Comment by fenziie** [comment]
> Move the setBlock line out of your generator and put it as instanceContainer.setBlock instead.

Oh thanks for the insanely quick reply!

**Comment by TheMode** [comment]
(you could use `setRelative` in the generator too)

**Comment by fenziie** [comment]
> (you could use `setRelative` in the generator too)

Okay, thanks.
