### ISSUE TITLE
LiteLoader throws NullPointerException

### ISSUE THREAD

**Issue by Alugor** [Minestom/Minestom#2380]
Hey,
correct me if I just use it in a wrong way but I discovered a bug with the Lightloader code snippet.

`Instant instant = Instant.now();
        // Initialization
        log.info("Starting minestom server..");
        MinecraftServer minecraftServer = MinecraftServer.init();

        // Create the instance
        log.debug("Creating server instance.");
        InstanceManager instanceManager = MinecraftServer.getInstanceManager();
        InstanceContainer instanceContainer = instanceManager.createInstanceContainer();

        // Set the ChunkGenerator
        log.debug("Setting up chunk generator.");
        instanceContainer.setGenerator(unit -> unit.modifier().fillHeight(0, 40, Block.GRASS_BLOCK));

        // Add an event callback to specify the spawning instance (and the spawn position)
        log.debug("Setting the spawn position.");
        instanceContainer.setBlock(0,99,0, Block.BEDROCK);
        instanceContainer.setChunkSupplier(LightingChunk::new);

        GlobalEventHandler globalEventHandler = MinecraftServer.getGlobalEventHandler();
        globalEventHandler.addListener(AsyncPlayerConfigurationEvent.class, event -> {
            final Player player = event.getPlayer();
            event.setSpawningInstance(instanceContainer);
            player.setRespawnPoint(new Pos(0, 100, 0));
        });

        // Start the server on port 25565
        minecraftServer.start("0.0.0.0", 25565);
        log.info("Server started. {}ms", Duration.between(instant, Instant.now()).toMillis());`

When joining - the lighting works partially but some chunks are also not loading at all.

This error is thrown:
`java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minestom.server.instance.light.Light.getLevel(int, int, int)" because "otherLight" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1489)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2071)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2033)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minestom.server.instance.light.Light.getLevel(int, int, int)" because "otherLight" is null
	at net.minestom.server.instance.light.BlockLight.buildExternalQueue(BlockLight.java:70)
	at net.minestom.server.instance.light.BlockLight.calculateExternal(BlockLight.java:198)
	at net.minestom.server.instance.LightingChunk.lambda$flushQueue$2(LightingChunk.java:394)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minestom.server.instance.light.Light.getLevel(int, int, int)" because "otherLight" is null`

**Comment by 0x7CD6** [comment]
The problem is that the chunk supplier (`LightingChunk::new`) is being set too late, causing problems when the instance is being used.  The way it's fixed is by moving the chunk supplier setup (`instanceContainer.setChunkSupplier(LightingChunk::new)`) *before* setting the chunk generator and adding event callbacks.

Here's the full code snipping I used when testing your code;
    ```
public static void main(String[] args) {
        MinecraftServer minecraftServer = MinecraftServer.init();

        // Create the instance
        InstanceManager instanceManager = MinecraftServer.getInstanceManager();
        InstanceContainer instanceContainer = instanceManager.createInstanceContainer();

        instanceContainer.setChunkSupplier(LightingChunk::new);

        // Set the ChunkGenerator
        instanceContainer.setGenerator(unit -> unit.modifier().fillHeight(0, 40, Block.GRASS_BLOCK));

        // Add an event callback to specify the spawning instance (and the spawn position)
        instanceContainer.setBlock(0,99,0, Block.BEDROCK);

        GlobalEventHandler globalEventHandler = MinecraftServer.getGlobalEventHandler();
        globalEventHandler.addListener(AsyncPlayerConfigurationEvent.class, event -> {
            final Player player = event.getPlayer();
            event.setSpawningInstance(instanceContainer);
            player.setRespawnPoint(new Pos(0, 100, 0));
        });

        // Start the server on port 25565
        minecraftServer.start("0.0.0.0", 25565);
    }
```

![image](https://github.com/user-attachments/assets/75d274a6-8601-405b-a061-bdd6cbc8e926)

**Comment by Alugor** [comment]
Thanks for looking into it - I'll try it as soon as I get home 👍🏻
