### ISSUE TITLE
UnsatisfiedLinkError: 'int io.netty.channel.unix.FileDescriptor.close(int)' in epoll availability check

### ISSUE THREAD

**Issue by kezz** [Minestom/Minestom#239]
I and others get the following stack trace when running the demo main method:

```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'int io.netty.channel.unix.FileDescriptor.close(int)'
	at io.netty.channel.unix.FileDescriptor.close(Native Method)
	at io.netty.channel.unix.FileDescriptor.close(FileDescriptor.java:83)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:46)
	at net.minestom.server.network.netty.NettyServer.init(NettyServer.java:114)
	at net.minestom.server.MinecraftServer.start(MinecraftServer.java:758)
	at demo.Main.main(Main.java:71)
```

For reference, I am getting this error on Ubuntu 20.04.2 using AdoptOpenJDK 15.0.2+7.

To workaround this issue, simple uncomment out the Epoll section in the `NettyServer` class.

**Comment by Eoghanmc22** [comment]
Fixed by f4c63ad
