### ISSUE TITLE
Exception when using Instance#getBlock(Pos)

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#2507]
Its rarely happening but if it happend, it was happening all the time for that specific block position. I do not know what caused that. Maybe someone else finds something from the Stacktrace
```
java.lang.IndexOutOfBoundsException: Index (12) is greater than or equal to list size (12)
        at it.unimi.dsi.fastutil.ints.IntArrayList.getInt(IntArrayList.java:341)
        at net.minestom.server.instance.palette.PaletteIndirect.get(PaletteIndirect.java:72)
        at net.minestom.server.instance.palette.AdaptivePalette.get(AdaptivePalette.java:30)
        at net.minestom.server.instance.DynamicChunk.getBlock(DynamicChunk.java:213)
        at net.minestom.server.utils.chunk.ChunkCache.getBlock(ChunkCache.java:40)
        at net.minestom.server.instance.Instance.getBlock(Instance.java:703)
        at net.minestom.server.instance.block.Block$Getter.getBlock(Block.java:239)
        at net.minestom.server.instance.block.Block$Getter.getBlock(Block.java:247)
        at dev.blu.engine.regain.lumberjack.task.RegainTreeTask.tick(RegainTreeTask.java:232)
```
```java
if (!instance.isChunkLoaded(pos)) {
  continue;
}

var block = instance.getBlock(pos); // This is line 232 in the stacktrace
```

**Comment by einfachBlu** [comment]
Still happening in the latest commit on master branch

**Comment by TheMeinerLP** [comment]
Can you update the Issue with a new Stacktrace with latest version ?
