### ISSUE TITLE
Light NullPointerException with a dimension when minY is 0 or above

### ISSUE THREAD

**Issue by leon0017** [Minestom/Minestom#2513]
To reproduce:
```java
InstanceManager instanceManager = MinecraftServer.getInstanceManager();

var dimension = DimensionType
        .builder()
        .minY(0)
        .height(256)
        .logicalHeight(256)
        .fixedTime(1000L)
        .bedWorks(false)
        .build();
var dimensionKey = MinecraftServer.getDimensionTypeRegistry().register("test:dimension0", dimension);

var instanceContainer = instanceManager.createInstanceContainer(dimensionKey);
instanceContainer.setGenerator(unit -> {
    unit.modifier().fillHeight(0, 40, Block.DIRT);
});
instanceContainer.setChunkSupplier(LightingChunk::new);
```

Exception:
```
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "net.minestom.server.instance.light.Light.getLevel(int, int, int)" because "otherLight" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minestom.server.instance.light.Light.getLevel(int, int, int)" because "otherLight" is null
	at net.minestom.server.instance.light.BlockLight.buildExternalQueue(BlockLight.java:72)
	at net.minestom.server.instance.light.BlockLight.calculateExternal(BlockLight.java:198)
	at net.minestom.server.instance.LightingChunk.lambda$flushQueue$2(LightingChunk.java:394)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	... 6 more
```

otherLight seems to be null because of this check being true:

```java
y - lighting.getMaxSection() >= 0
```

https://github.com/Minestom/Minestom/blob/d760a60a5c03bf25b680c2af70c5fab99f7d45ec/src/main/java/net/minestom/server/instance/LightingChunk.java#L359

I think it might have to do with another exception that occurs with generation when minY is set to a value above 0, like 16, not sure though:
```
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:687)
	at net.minestom.server.instance.generator.GeneratorImpl.findAbsolute(GeneratorImpl.java:526)
	at net.minestom.server.instance.generator.GeneratorImpl$AreaModifierImpl.findAbsoluteSection(GeneratorImpl.java:428)
	at net.minestom.server.instance.generator.GeneratorImpl$AreaModifierImpl.fillHeight(GeneratorImpl.java:420)
	at net.minestom.demo.PlayerInit.lambda$new$15(PlayerInit.java:228)
	at net.minestom.server.instance.InstanceContainer.createChunk(InstanceContainer.java:383)
	at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$7(InstanceContainer.java:328)
	at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$8(InstanceContainer.java:345)
	at java.base/java.lang.VirtualThread.run(VirtualThread.java:329)
```

**Comment by im-a-blobfish** [comment]
the issue actually appears to happen with any minY above -16

**Comment by SnowzNZ** [comment]
Fixed in #2752
