### ISSUE TITLE
Exception + Timeout when trying to break a block

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#2528]
No clue what causes it. Just know that its happening when trying to break a block. In my system, i use the AnimationEvent to proceed. So it could be also the BlockBreakAnimationPacket

java.lang.IllegalArgumentException: New size is the same as the current size
        at net.minestom.server.network.NetworkBufferImpl.resize(NetworkBufferImpl.java:202)
        at net.minestom.server.network.packet.PacketWriting.writeQueue(PacketWriting.java:205)
        at net.minestom.server.network.player.PlayerSocketConnection.flushSync(PlayerSocketConnection.java:427)
        at net.minestom.server.network.socket.Server.playerWriteLoop(Server.java:115)
        at net.minestom.server.network.socket.Server.lambda$start$1(Server.java:75)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)

**Comment by mworzala** [comment]
Closing as duplicate of https://github.com/Minestom/Minestom/issues/2530, still I need more information.
