### ISSUE TITLE
Exception that timeout players very often

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#2530]
Happening when i change the instance for a player.

java.lang.IllegalArgumentException: New size is the same as the current size
        at net.minestom.server.network.NetworkBufferImpl.resize(NetworkBufferImpl.java:202)
        at net.minestom.server.network.packet.PacketWriting.writeQueue(PacketWriting.java:205)
        at net.minestom.server.network.player.PlayerSocketConnection.flushSync(PlayerSocketConnection.java:427)
        at net.minestom.server.network.socket.Server.playerWriteLoop(Server.java:115)
        at net.minestom.server.network.socket.Server.lambda$start$1(Server.java:75)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)

**Comment by mworzala** [comment]
Should be fixed in https://github.com/Minestom/Minestom/commit/c96413678cf9e7dad016bbb3b76bf4396e434331
