### ISSUE TITLE
Exception when using AbsoluteBlockBatch#setBlock(Point, Block)

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#2540]
This exception came into the console. It happend quite frequently and often but i cant exactly force it.
The block is not placed when that error occur

java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at it.unimi.dsi.fastutil.ints.IntArrayList.add(IntArrayList.java:334)
	at net.minestom.server.instance.palette.PaletteIndirect.getPaletteIndex(PaletteIndirect.java:276)
	at net.minestom.server.instance.palette.PaletteIndirect.set(PaletteIndirect.java:87)
	at net.minestom.server.instance.palette.AdaptivePalette.set(AdaptivePalette.java:48)
	at net.minestom.server.instance.DynamicChunk.setBlock(DynamicChunk.java:92)
	at net.minestom.server.instance.LightingChunk.setBlock(LightingChunk.java:159)
	at net.minestom.server.instance.Chunk.setBlock(Chunk.java:94)
	at net.minestom.server.instance.batch.ChunkBatch.apply(ChunkBatch.java:216)
	at net.minestom.server.instance.batch.ChunkBatch.singleThreadFlush(ChunkBatch.java:188)
	at net.minestom.server.instance.batch.ChunkBatch.lambda$apply$0(ChunkBatch.java:156)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)

**Comment by TheMeinerLP** [comment]
Can you provide some code of reproduce ?
