### ISSUE TITLE
Torch exception when using facing property

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#2542]
When i use the facing property on the PlacementRule for Torches it throws that exception whenever i place a torch. In the game it correctly displays the torch facing even tho the exception is spammed

```java
@Override
  public @Nullable Block blockPlace(@NotNull PlacementState placementState) {
    var block = placementState.block();
    var blockFace = placementState.blockFace();

    if (blockFace == null) {
      return block;
    }

    return block.withProperty("facing", blockFace.name());
  }
```

```

java.lang.IllegalArgumentException: Property facing is not valid for block minecraft:torch{properties={}, nbt=null, handler=null}
	at net.minestom.server.instance.block.BlockImpl.findKeyIndex(BlockImpl.java:240)
	at net.minestom.server.instance.block.BlockImpl.withProperty(BlockImpl.java:132)
	at dev.blu.engine.block.rules.TorchRule.blockPlace(TorchRule.java:25)
	at net.minestom.server.instance.InstanceContainer.UNSAFE_setBlock(InstanceContainer.java:184)
	at net.minestom.server.instance.InstanceContainer.placeBlock(InstanceContainer.java:213)
	at net.minestom.server.listener.BlockPlacementListener.listener(BlockPlacementListener.java:174)
	at net.minestom.server.listener.manager.PacketListenerManager.lambda$setPlayListener$3(PacketListenerManager.java:163)
	at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:132)
	at net.minestom.server.entity.Player.lambda$interpretPacketQueue$14(Player.java:2083)
	at org.jctools.queues.MpscArrayQueue.drain(MpscArrayQueue.java:512)
	at net.minestom.server.entity.Player.interpretPacketQueue(Player.java:2083)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at net.minestom.server.network.ConnectionManager.tick(ConnectionManager.java:326)
	at net.minestom.server.ServerProcessImpl$TickerImpl.tick(ServerProcessImpl.java:376)
	at net.minestom.server.thread.TickSchedulerThread.run(TickSchedulerThread.java:29)
```

**Comment by mworzala** [comment]
This is correct - `minecraft:torch` is only the standing torch, `minecraft:wall_torch` is used for wall attachment and has the facing property.
