### ISSUE TITLE
Disconnect Exception

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#2545]
Does not happen every time and pretty rare but depending if you have some players switching in and out, the error came quite often to me.
```
java.nio.channels.AsynchronousCloseException
        at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:203)
        at java.base/sun.nio.ch.SocketChannelImpl.endRead(SocketChannelImpl.java:396)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:436)
        at net.minestom.server.network.NetworkBufferImpl.readChannel(NetworkBufferImpl.java:259)
        at net.minestom.server.network.player.PlayerSocketConnection.read(PlayerSocketConnection.java:105)
        at net.minestom.server.network.socket.Server.playerReadLoop(Server.java:99)
        at net.minestom.server.network.socket.Server.lambda$start$0(Server.java:74)
        at java.base/java.lang.VirtualThread.run(VirtualThread.java:311)
```

**Comment by leon0017** [comment]
This was fixed in [187931e](https://github.com/Minestom/Minestom/commit/187931e50b6633a510d2b05302693de703593410)
