### ISSUE TITLE
Inventory drag itemstack error

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#2546]
No clue what happend there but the stacktrace might help finding the issue
```
java.lang.ArrayIndexOutOfBoundsException: Index 51 out of bounds for length 46
        at java.base/jdk.internal.util.Preconditions$2.apply(Preconditions.java:63)
        at java.base/jdk.internal.util.Preconditions$2.apply(Preconditions.java:60)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
        at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:98)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
        at java.base/java.lang.invoke.VarHandleReferences$Array.getVolatile(VarHandleReferences.java:604)
        at net.minestom.server.inventory.AbstractInventory.getItemStack(AbstractInventory.java:241)
        at net.minestom.server.inventory.Inventory.dragging(Inventory.java:282)
        at net.minestom.server.listener.WindowListener.clickWindowListener(WindowListener.java:63)
        at net.minestom.server.listener.manager.PacketListenerManager.lambda$setPlayListener$3(PacketListenerManager.java:163)
        at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:132)
        at net.minestom.server.entity.Player.lambda$interpretPacketQueue$14(Player.java:2083)
        at org.jctools.queues.MpscArrayQueue.drain(MpscArrayQueue.java:512)
        at net.minestom.server.entity.Player.interpretPacketQueue(Player.java:2083)
        at net.minestom.server.entity.Player.update(Player.java:379)
        at net.minestom.server.entity.Entity.tick(Entity.java:566)
        at net.minestom.server.thread.TickThread.tick(TickThread.java:78)
        at net.minestom.server.thread.TickThread.run(TickThread.java:53)
```

**Comment by TheMeinerLP** [comment]
Can you provide some code of reproduce ?
