### ISSUE TITLE
Exception with Instance#setBlock

### ISSUE THREAD

**Issue by einfachBlu** [Minestom/Minestom#2547]
These exceptions come when i set blocks. Not happening every time and i cant reproduce that all the time but might help finding the issue based on the stacktrace

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 4 out of bounds for int[3]
	at java.base/java.lang.System.arraycopy(Native Method)
	at it.unimi.dsi.fastutil.ints.IntArrays.forceCapacity(IntArrays.java:126)
	at it.unimi.dsi.fastutil.ints.IntArrayList.grow(IntArrayList.java:317)
	at it.unimi.dsi.fastutil.ints.IntArrayList.add(IntArrayList.java:333)
	at net.minestom.server.instance.palette.PaletteIndirect.getPaletteIndex(PaletteIndirect.java:276)
	at net.minestom.server.instance.palette.PaletteIndirect.set(PaletteIndirect.java:87)
	at net.minestom.server.instance.palette.AdaptivePalette.set(AdaptivePalette.java:48)
	at net.minestom.server.instance.DynamicChunk.setBlock(DynamicChunk.java:92)
	at net.minestom.server.instance.LightingChunk.setBlock(LightingChunk.java:159)
	at net.minestom.server.instance.InstanceContainer.UNSAFE_setBlock(InstanceContainer.java:189)
	at net.minestom.server.instance.InstanceContainer.setBlock(InstanceContainer.java:129)
	at net.minestom.server.instance.Instance.setBlock(Instance.java:179)
	at net.minestom.server.instance.block.Block$Setter.setBlock(Block.java:231)
	at dev.blu.engine.common.block.AsyncBlockBatch.lambda$apply$2(AsyncBlockBatch.java:81)
	at dev.blu.engine.common.async.AsyncHandler.lambda$run$1(AsyncHandler.java:84)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at it.unimi.dsi.fastutil.ints.IntArrayList.add(IntArrayList.java:334)
	at net.minestom.server.instance.palette.PaletteIndirect.getPaletteIndex(PaletteIndirect.java:276)
	at net.minestom.server.instance.palette.PaletteIndirect.set(PaletteIndirect.java:87)
	at net.minestom.server.instance.palette.AdaptivePalette.set(AdaptivePalette.java:48)
	at net.minestom.server.instance.DynamicChunk.setBlock(DynamicChunk.java:92)
	at net.minestom.server.instance.LightingChunk.setBlock(LightingChunk.java:159)
	at net.minestom.server.instance.Chunk.setBlock(Chunk.java:94)
	at net.minestom.server.instance.batch.ChunkBatch.apply(ChunkBatch.java:216)
	at net.minestom.server.instance.batch.ChunkBatch.singleThreadFlush(ChunkBatch.java:188)
	at net.minestom.server.instance.batch.ChunkBatch.lambda$apply$0(ChunkBatch.java:156)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
```

**Comment by mworzala** [comment]
The trace here seems to be related to fastutil (the Minestom call is just `#add`), however I dont see any [related issues](https://github.com/vigna/fastutil/issues?q=is%3Aissue+is%3Aopen+arraycopy+last+source+index+) on fastutils side so it is likely on our side. I will need more information to debug further.
