### ISSUE TITLE
MinecraftServer.stopCleanly() throws an error if a player is logged in when called.

### ISSUE THREAD

**Issue by GreatWyrm** [Minestom/Minestom#511]
### The Bug
Whenever I've got an account logged in to a Minestom server and run my /stop command (basically just calls `MinecraftServer.stopCleanly()`), I get an error with the following stacktrace:

`java.nio.channels.ClosedChannelException
        at java.base/sun.nio.ch.SocketChannelImpl.ensureOpenAndConnected(SocketChannelImpl.java:215)
        at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:527)
        at net.minestom.server.utils.binary.BinaryBuffer.writeChannel(BinaryBuffer.java:144)
        at net.minestom.server.network.player.PlayerSocketConnection.flush(PlayerSocketConnection.java:293)
        at net.minestom.server.network.player.PlayerSocketConnection.writeAndFlush(PlayerSocketConnection.java:271)
        at net.minestom.server.entity.Player.kick(Player.java:1400)
        at net.minestom.server.entity.Player.remove(Player.java:475)
        at net.minestom.server.network.ConnectionManager.shutdown(ConnectionManager.java:350)
        at net.minestom.server.MinecraftServer.stopCleanly(MinecraftServer.java:721)
        at me.arcanewarrior.com.commands.StopCommand.lambda$new$0(StopCommand.java:13)
        at net.minestom.server.command.builder.ParsedCommand.execute(ParsedCommand.java:67)
        at net.minestom.server.command.builder.CommandDispatcher.execute(CommandDispatcher.java:94)
        at net.minestom.server.command.CommandManager.execute(CommandManager.java:111)
        at net.minestom.server.listener.ChatMessageListener.listener(ChatMessageListener.java:34)
        at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:100)
        at net.minestom.server.network.packet.client.ClientPlayPacket.process(ClientPlayPacket.java:19)
        at net.minestom.server.entity.Player.update(Player.java:306)
        at net.minestom.server.entity.Entity.tick(Entity.java:467)
        at net.minestom.server.thread.TickThread.tick(TickThread.java:69)
        at net.minestom.server.thread.TickThread.run(TickThread.java:41)`

### Potential Explanation

Following the stacktrace, I noticed that the ConnectionManager's shutdown method calls these lines:
`playerConnection.sendPacket(disconnectPacket);`
`playerConnection.flush();`
`player.remove();`

But the `player.remove();` line eventually leads into this line (in the kick() function that it calls at the end):
`((PlayerSocketConnection) playerConnection).writeAndFlush(disconnectPacket);`
`playerConnection.disconnect();`

So Minestom is sending 2 disconnect packets and flushing the connection twice, which I believe is the cause of the error.

**Comment by TheMode** [comment]
Fixed by ae08ac29872fdd394d261c20587efd5ebead3c6f
