### ISSUE TITLE
1.18: Loading a saved instance

### ISSUE THREAD

**Issue by UnrealValentin** [Minestom/Minestom#559]
When loading a saved instance, this happens:
```
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at Minestom Root ClassLoader//org.jglrxavpok.hephaistos.mca.ChunkSection.<init>(ChunkSection.kt:158)
	at Minestom Root ClassLoader//org.jglrxavpok.hephaistos.mca.ChunkColumn.<init>(ChunkColumn.kt:200)
	at Minestom Root ClassLoader//org.jglrxavpok.hephaistos.mca.RegionFile.readColumn(RegionFile.kt:184)
	at Minestom Root ClassLoader//org.jglrxavpok.hephaistos.mca.RegionFile.getChunk$lambda-3(RegionFile.kt:110)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at Minestom Root ClassLoader//org.jglrxavpok.hephaistos.mca.RegionFile.getChunk(RegionFile.kt:110)
	at Minestom Root ClassLoader//net.minestom.server.instance.AnvilLoader.loadMCA(AnvilLoader.java:86)
	at Minestom Root ClassLoader//net.minestom.server.instance.AnvilLoader.loadChunk(AnvilLoader.java:75)
	at Minestom Root ClassLoader//net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$9(InstanceContainer.java:259)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```
works with 1.17 worlds, not with 1.18 worlds.

**Comment by UnrealValentin** [comment]
[1.zip](https://github.com/Minestom/Minestom/files/7781345/1.zip)
1.18 world that won't load.

**Comment by UnrealValentin** [comment]
just tested in vanilla, world can't be loaded. saving seems to be the problem.

**Comment by ElAndree** [comment]
I can also reproduce it.

**Comment by UnrealValentin** [comment]
Loading a vanilla generated (1.18) world also doesn't work

**Comment by UnrealValentin** [comment]
@jglrxavpok should look into this.

**Comment by Marlonzockt** [comment]
I just did a little testing myself, and found out that you actually can copy the region files from < 1.18 worlds, so for example from 1.17.1 world, but not from 1.18 world.

**Comment by jglrxavpok** [comment]
Reopened: requires change on the Minestom-side
Coming very soon

**Comment by jglrxavpok** [comment]
Should now be fixed
