### ISSUE TITLE
ArrayIndexOutOfBoundsException on block update at vertical instance limit

### ISSUE THREAD

**Issue by Marlonzockt** [Minestom/Minestom#568]
When breaking or placing a block at the world min/max y in an InstanceContainer, an ArrayIndexOutOfBoundsException gets thrown

**Comment by Marlonzockt** [comment]
Stacktrace for breaking:

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680)
	at net.minestom.server.instance.DynamicChunk.getSection(DynamicChunk.java:106)
	at net.minestom.server.instance.Chunk.getSectionAt(Chunk.java:94)
	at net.minestom.server.instance.DynamicChunk.getBlock(DynamicChunk.java:133)
	at net.minestom.server.instance.block.Block$Getter.getBlock(Block.java:226)
	at net.minestom.server.instance.InstanceContainer.executeNeighboursBlockPlacementRule(InstanceContainer.java:499)
	at net.minestom.server.instance.InstanceContainer.UNSAFE_setBlock(InstanceContainer.java:135)
	at net.minestom.server.instance.InstanceContainer.breakBlock(InstanceContainer.java:187)
	at net.minestom.server.listener.PlayerDiggingListener.breakBlock(PlayerDiggingListener.java:145)
	at net.minestom.server.listener.PlayerDiggingListener.startDigging(PlayerDiggingListener.java:67)
	at net.minestom.server.listener.PlayerDiggingListener.playerDiggingListener(PlayerDiggingListener.java:31)
	at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:100)
	at net.minestom.server.entity.Player.lambda$update$3(Player.java:318)
	at org.jctools.queues.MessagePassingQueueUtil.drain(MessagePassingQueueUtil.java:53)
	at org.jctools.queues.MpUnboundedXaddArrayQueue.drain(MpUnboundedXaddArrayQueue.java:435)
	at org.jctools.queues.MpscUnboundedXaddArrayQueue.drain(MpscUnboundedXaddArrayQueue.java:28)
	at net.minestom.server.entity.Player.update(Player.java:318)
	at net.minestom.server.entity.Entity.tick(Entity.java:538)
	at net.minestom.server.thread.TickThread.tick(TickThread.java:69)
	at net.minestom.server.thread.TickThread.run(TickThread.java:41)
	
	Stacktrace for placing:
	
	java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 16
	at java.base/java.util.ImmutableCollections$ListN.get(ImmutableCollections.java:680)
	at net.minestom.server.instance.DynamicChunk.getSection(DynamicChunk.java:106)
	at net.minestom.server.instance.Chunk.getSectionAt(Chunk.java:94)
	at net.minestom.server.instance.DynamicChunk.getBlock(DynamicChunk.java:133)
	at net.minestom.server.instance.block.Block$Getter.getBlock(Block.java:226)
	at net.minestom.server.instance.InstanceContainer.executeNeighboursBlockPlacementRule(InstanceContainer.java:499)
	at net.minestom.server.instance.InstanceContainer.UNSAFE_setBlock(InstanceContainer.java:135)
	at net.minestom.server.instance.InstanceContainer.placeBlock(InstanceContainer.java:160)
	at net.minestom.server.listener.BlockPlacementListener.listener(BlockPlacementListener.java:155)
	at net.minestom.server.listener.manager.PacketListenerManager.processClientPacket(PacketListenerManager.java:100)
	at net.minestom.server.entity.Player.lambda$update$3(Player.java:318)
	at org.jctools.queues.MessagePassingQueueUtil.drain(MessagePassingQueueUtil.java:53)
	at org.jctools.queues.MpUnboundedXaddArrayQueue.drain(MpUnboundedXaddArrayQueue.java:435)
	at org.jctools.queues.MpscUnboundedXaddArrayQueue.drain(MpscUnboundedXaddArrayQueue.java:28)
	at net.minestom.server.entity.Player.update(Player.java:318)
	at net.minestom.server.entity.Entity.tick(Entity.java:538)
	at net.minestom.server.thread.TickThread.tick(TickThread.java:69)
	at net.minestom.server.thread.TickThread.run(TickThread.java:41)
