### ISSUE TITLE
World Bugging on Join

### ISSUE THREAD

**Issue by sqcred** [Minestom/Minestom#627]
Sometimes when i join my server after it restarted + the world saved (instance.saveInstance() + instance.saveChunksToStorage())
i get this error and when i join some chunks are completely gone

java.lang.NegativeArraySizeException: -1828709181
	at org.jglrxavpok.hephaistos.mca.RegionFile.readColumnData(RegionFile.kt:163)
	at org.jglrxavpok.hephaistos.mca.RegionFile.readColumn(RegionFile.kt:184)
	at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk$lambda-3(RegionFile.kt:110)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk(RegionFile.kt:110)
	at net.minestom.server.instance.AnvilLoader.loadMCA(AnvilLoader.java:80)
	at net.minestom.server.instance.AnvilLoader.loadChunk(AnvilLoader.java:69)
	at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$9(InstanceContainer.java:261)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by jglrxavpok** [comment]
Did you get any other when saving the chunks?

**Comment by sqcred** [comment]
Yes the same error

**Comment by jglrxavpok** [comment]
Can you open the world in vanilla?

**Comment by emortaldev** [comment]
What event is the `instance.saveInstance()` in?

**Comment by sqcred** [comment]
Well i dont really know why it is happening. When i start the server with a new world and i save it, it works. but if i restart it inside my ide it throws this error. + now i get this one

org.jglrxavpok.hephaistos.mca.AnvilException: Invalid compression type: 34 (only 1 and 2 known)
	at org.jglrxavpok.hephaistos.mca.RegionFile.readColumnData(RegionFile.kt:170)
	at org.jglrxavpok.hephaistos.mca.RegionFile.readColumn(RegionFile.kt:184)
	at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk$lambda-3(RegionFile.kt:110)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
	at org.jglrxavpok.hephaistos.mca.RegionFile.getChunk(RegionFile.kt:110)
	at net.minestom.server.instance.AnvilLoader.loadMCA(AnvilLoader.java:80)
	at net.minestom.server.instance.AnvilLoader.loadChunk(AnvilLoader.java:69)
	at net.minestom.server.instance.InstanceContainer.lambda$retrieveChunk$9(InstanceContainer.java:261)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by sqcred** [comment]
i have an autosave system wich calls both methods every 5 minutes + 

Runtime.getRuntime().addShutdownhook()

**Comment by emortaldev** [comment]
Instead of using runtime, try using Minestom's scheduler to add a shutdown task

**Comment by TheMode** [comment]
`AnvilLoader` now has a completely different implementation
