### ISSUE TITLE
Server refuses input after trying to interact with terminal using mouse in any way

### ISSUE THREAD

**Issue by cody-quinn** [Minestom/Minestom#894]
When I try to use the terminal with my mouse in any way, usually on accident, the following error occurs and no more inputs are processed. The server does not crash however, and I have to manually kill the process with htop or kill.

The terminal I'm using is Alacritty.

```
Exception in thread "Jline" java.lang.NoClassDefFoundError: org/jline/terminal/Terminal$MouseTracking
	at org.jline.reader.impl.LineReaderImpl.doCleanup(LineReaderImpl.java:2540)
	at org.jline.reader.impl.LineReaderImpl.cleanup(LineReaderImpl.java:2526)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:727)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468)
	at net.minestom.server.terminal.MinestomTerminal.lambda$start$0(MinestomTerminal.java:36)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.jline.terminal.Terminal$MouseTracking
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 6 more
```

**Comment by cody-quinn** [comment]
Terminal removed from Minestom
